name: xrd_simulator_env
dependencies:
  - python=3.13
  - numpy
  - scipy
  - matplotlib
  - setuptools
  - pandas
  - numba
  - dill
  - CifFile
  - pillow
  - scikit-image
  - psutil
  - pip
  - pip:
      - torch
      - pyFAI
      - xfab
      - meshio
      - meshpy
