name: macos conda-build

on: [push]


jobs:
  build-mac:
    runs-on: macos-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Setup micromamba
      uses: mamba-org/provision-with-micromamba@v15
      with:
        environment-name: xrd-sim-env
        extra-specs: python=3.13
    - name: Install dependencies
      run: |
        python --version
        micromamba install -c conda-forge xrd_simulator
    - name: Lint with flake8
      run: |
        micromamba install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=xfab
    - name: Test with pytest
      run: |
        micromamba install pytest
        pytest